name: Lint, test and build
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    env:
      X_API_KEY: ${{ secrets.X-API-KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: Install yarn
        run: npm install --global yarn

      - name: Install modules
        run: yarn install

      - name: Linting ts
        run: yarn lint:ts

      - name: Linting scss
        run: yarn lint:scss

      - name: Testing
        run: yarn test

      - name: Build
        run: yarn build
