name: linting, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    env:
      X_API_KEY: ${{ secrets.X_API_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Starting Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}

      - name: install modules
        run: npm install

      - name: linting
        run: npm run lint
        if: always()

      - name: build
        run: npm run build
